Improving blackfire docs
platformsh/platformsh-docs pull request #1851
Opened 2021-08-06 08:16 UTC by matthiaz

Going through the documentation on how to setup blackfire I noticed some things that can be improved.

2021-08-06 08:21 UTC, lolautruche requested changes
Thank you @matthiaz!
By the way, you may check the presence and version of Blackfire probe by running php -v 😉

2021-08-06 08:21 UTC, lolautruche commented on docs/src/integrations/profiling/blackfire.md
> +platform variable:create -e master --json=false --visible-build=false --sensitive=true --level=project env:BLACKFIRE_SERVER_ID --value <insert your Server ID>
It is actually not a sensitive variable 😉

2021-08-11 12:31 UTC, chadwcarlson commented on docs/src/integrations/profiling/blackfire.md
> +platform variable:create -e master --json=false --visible-build=false --sensitive=true --level=project env:BLACKFIRE_SERVER_ID --value <insert your Server ID>
```suggestion
platform variable:create -e master --json=false --visible-build=false --level=project env:BLACKFIRE_SERVER_ID --value <insert your Server ID>
```

2021-08-11 12:42 UTC, chadwcarlson commented on docs/src/integrations/profiling/blackfire.md
> +platform variable:create -e=<insert your branch name> --json=false --visible-build=false --sensitive=true --level=environment env:BLACKFIRE_SERVER_ID --value <insert your Server ID>
```suggestion
platform variable:create -e=<insert your branch name> --json=false --visible-build=false --level=environment env:BLACKFIRE_SERVER_ID --value <insert your Server ID>
```

2021-08-11 13:06 UTC, lolautruche requested changes

2021-08-11 13:06 UTC, lolautruche commented on docs/src/integrations/profiling/blackfire.md
> +platform variable:create -e master --json=false --visible-build=false --sensitive=true --level=project env:BLACKFIRE_SERVER_TOKEN --value <insert your Server Token>
```suggestion
platform variable:create -e master --json=false --visible-build=false --sensitive=false --level=project env:BLACKFIRE_SERVER_ID --value <insert your Server ID>
platform variable:create -e master --json=false --visible-build=false --sensitive=false --level=project env:BLACKFIRE_SERVER_TOKEN --value <insert your Server Token>
```

2021-08-11 13:06 UTC, lolautruche commented on docs/src/integrations/profiling/blackfire.md
> +platform variable:create -e=<insert your branch name> --json=false --visible-build=false --sensitive=true --level=environment env:BLACKFIRE_SERVER_TOKEN --value <insert your Server Token>
```suggestion
platform variable:create -e=<insert your branch name> --json=false --visible-build=false --level=environment --sensitive=false env:BLACKFIRE_SERVER_ID --value <insert your Server ID>
platform variable:create -e=<insert your branch name> --json=false --visible-build=false --sensitive=false --level=environment env:BLACKFIRE_SERVER_TOKEN --value <insert your Server Token>
```

2021-08-11 13:32 UTC, lolautruche commented
The branch needs to be rebased before merging 😉

2021-08-11 13:48 UTC, chadwcarlson commented
@lolautruche resubmitted here for less of a mess https://github.com/platformsh/platformsh-docs/pull/1854

2021-08-13 13:08 UTC, closed without merging