:art: Routes port limit info
platformsh/platformsh-docs pull request #2067
Opened 2021-12-29 10:39 UTC by trolologuy

## Why

Closes #2035

## What's changed

2021-12-29 11:31 UTC, trolologuy commented
We should probably also add a link to the `/configuration/routes/https.md` page

2022-01-04 08:55 UTC, CollierCZ commented on docs/src/configuration/routes/_index.md
> +- {{% lets_encrypt_limitations %}}
This won't work without #2069 first

2022-01-20 13:34 UTC, trolologuy commented
See [the changes in 2069](https://github.com/platformsh/platformsh-docs/pull/2069/files#diff-d178dfa638c867651b2acf1f91a1e9454e4009974d5b7a275aac5132edbaeda0) for the `{{% lets_encrypt_limitations %}}` placeholder.

2022-01-20 14:36 UTC, CollierCZ requested changes
I like the idea of a list to present the two options. It slightly goes away from one recommendation and a backup, but I think that's probably fine like that. I don't really know myself.

The use of the transclusion is also :+1: And great to include the ports info, which seems to have gone missing :detective: 

I'd just point out some minor points to get the style consistent. Partly it seems to come from making things more formal (using modals and being longer). I'd try to aim for more short and direct:
* https://developers.google.com/style/word-list?hl=en#should Note the examples under "A state is actual" -- this kind of modal verb can be difficult for some language learners
* I feel like "too big" is clearer than "an excessive size"
* https://developers.google.com/style/lists?hl=en#capitalization-and-end-punctuation There's a habit that I see often in formal and academic writing to treat lists as part of the sentence that surround them. This can sometimes be harder to parse. Treat the list as separate from what surrounds it -- like someone might be scanning the page and stop at just the list.
* Remember to use relative links: https://github.com/platformsh/platformsh-docs/blob/main/contributing/markup-format.md#links

2022-01-20 14:36 UTC, CollierCZ commented on docs/src/configuration/routes/_index.md
> +- move any redirect routes to the application,
```suggestion
- move redirect routes to the application,
```
`any` implies that there might not be any, but if the file is rejected for being too big, I think there have to be some.

2022-01-21 07:50 UTC, CollierCZ approved these changes
Looks good to me :rocket:

2022-01-21 07:54 UTC, merged