📝 Note that .htaccess files are ignored
platformsh/platformsh-docs pull request #2335
Opened 2022-05-09 07:39 UTC by CollierCZ

## Why

To make sure it's clear. See context for request.

## What's changed

Added a note at the end of the routes page since it didn't seem important enough to go at the beginning and didn't fit elsewhere.

2022-05-10 06:39 UTC, CollierCZ commented on docs/src/define-routes/_index.md
> +Accomplish the same goals with routes, logic in your app, and [web server locations](../create-apps/web/_index.md).
It's not only redirection, is it? I thought it could also be things like error responses and access control.

2022-05-11 09:25 UTC, trolologuy commented on docs/src/define-routes/_index.md
> +Accomplish the same goals with routes, logic in your app, and [web server locations](../create-apps/web/_index.md).
You are right, indeed the .htaccess can be used for much more than just redirections.

2022-05-11 09:26 UTC, trolologuy approved these changes
✅ 🚀

2022-05-11 09:27 UTC, trolologuy requested changes

2022-05-11 09:27 UTC, trolologuy commented on docs/src/define-routes/_index.md
> +## `.htacess` files
Hmmm I mistakenly added an extra space there.

2022-05-11 09:28 UTC, trolologuy requested changes

2022-05-11 09:28 UTC, trolologuy commented on docs/src/define-routes/_index.md
> +## `. htaccess` files
:clipboard: :warning: 
```suggestion
## `.htaccess` files
```
Sorry, didn't see the extra space previously.

2022-05-12 13:40 UTC, trolologuy approved these changes
✅ 🚀

2022-05-12 14:16 UTC, merged