📝 Rework region migration instructions
platformsh/platformsh-docs pull request #2436
Opened 2022-06-22 14:36 UTC by CollierCZ

- 📝 Clarify region availability
- 📝 Rework region migration

## Why

Closes #2418

## What's changed

Redid the page to find the style guide and templates

2022-06-24 09:51 UTC, trolologuy requested changes
A couple typos, but other than that, great change! The migration guide is much better now 😍 

- [x] Final built pages are working as expected.
- [x] The information is correct.
- [x] The information is comprehensive.
- [x] The information is concise.
- [x] The information is clear.

2022-06-24 09:51 UTC, trolologuy commented on docs/src/development/regions.md
> +Each organization can have its own rules for what regions to allow
:clipboard:
```suggestion
Each organization can have its own rules for what regions to allow.
```

2022-06-24 09:51 UTC, trolologuy commented on docs/src/development/regions.md
> +See a [list of not included features](../projects/region-migration.md#why-migrate-between-regions)
:clipboard:
```suggestion
See a [list of not included features](../projects/region-migration.md#why-migrate-between-regions).
```

2022-06-27 07:09 UTC, CollierCZ commented on docs/src/development/regions.md
> +Each organization can have its own rules for what regions to allow
```suggestion
Each organization can have its own rules for what regions to allow.
```

2022-06-27 07:52 UTC, trolologuy approved these changes
✅

2022-06-27 07:53 UTC, merged