🚨 Decrease number of warnings and suggestions
platformsh/platformsh-docs pull request #2547
Opened 2022-09-16 11:32 UTC by CollierCZ

## Why

Linting was failing

## What's changed

Trying with fewer warnings to see if it helps

2022-09-26 13:21 UTC, trolologuy requested changes
Still some linting warning that could be solved.
Tried to improve phrases and solve simple linting warnings that were left.
Skipped DNS and PHP

Many warnings left for:
- that is -> that's  
- do not -> don't
- should not -> shouldn't
- it is -> it's
- We
- will
- sentences starting with "There are"
- Please

One of the comments recommends the "use 'that is' instead of 'i.e.'", but it should be "that's".
Heavy repetition of "Platform.sh".
Lack of consistency, users / customers / ... instead of "You".

2022-09-26 13:21 UTC, trolologuy commented on docs/src/security/updates.md
> +These do not always happen immediately but when a security vulnerability is identified and released it tends to be fairly soon after.
:hammer_and_wrench:
```suggestion
These don't always happen immediately but when a security vulnerability is identified and released it tends to be fairly soon after.
```

2022-09-26 13:21 UTC, trolologuy requested changes
Still some linting warning that could be solved.
Tried to improve phrases and solve simple linting warnings that were left.
Skipped DNS and PHP

Many warnings left for:
- that is -> that's  
- do not -> don't
- should not -> shouldn't
- it is -> it's
- We
- will
- sentences starting with "There are"
- Please

One of the comments recommends the "use 'that is' instead of 'i.e.'", but it should be "that's".
Heavy repetition of "Platform.sh".
Lack of consistency, users / customers / ... instead of "You".

2022-09-26 14:42 UTC, CollierCZ reviewed
As I noted in chat, the scope of the task was not to eliminate warnings. It was just to preserve work that was don't with global find & replace.

So any suggestions that required judgment, back and forth, or anything other than clicking `Add suggestion to batch`, I resolved as out of scope. I think GitHub lost some I did add to the batch, but I hope it's OK anyway.

`that's` does not work as a replacement for `i.e.`, only `that is` does. Warnings and suggestions are things to think about rather than absolute rules (which is why they're not errors).

Most of the other things will be fixed as we go through the docs rework.

2022-09-26 14:42 UTC, CollierCZ commented on docs/src/development/troubleshoot.md
Out of scope

2022-09-26 14:42 UTC, CollierCZ commented on docs/src/gettingstarted/developing/_index.md
> +  Once an app has been migrated to Platform.sh, you have many more features that help improve your development life cycle. You can build your site locally, remotely connect to your services, and test
Out of scope

2022-09-26 14:42 UTC, CollierCZ commented on docs/src/gettingstarted/developing/dev-environments/download-code.md
> +    You need the your *project ID*. You can retrieve this ID at any time using the CLI commands `platform` or `platform project:list`.
Second comment out of scope

2022-09-26 14:42 UTC, CollierCZ commented on docs/src/gettingstarted/developing/local-development/build-locally.md
Out of scope

2022-09-26 14:42 UTC, CollierCZ commented on docs/src/gettingstarted/next-steps/going-live/set-domain.md
> +You need to configure your registered domain on your Platform.sh project before going live, and you can do that either through the Console or by using the CLI.
Out of scope

2022-09-26 14:42 UTC, CollierCZ commented on docs/src/gettingstarted/next-steps/going-live/set-domain.md
Out of scope

2022-09-26 14:42 UTC, CollierCZ commented on docs/src/gettingstarted/next-steps/integrations.md
Out of scope

2022-09-26 14:42 UTC, CollierCZ commented on docs/src/guides/drupal9/deploy/deploy.md
Out of scope

2022-09-26 14:42 UTC, CollierCZ commented on docs/src/guides/drupal9/elasticsearch.md
> +If you do not already have the Platform.sh Config Reader library installed and referenced at the top of the file, you need to install it with `composer require platformsh/config-reader` and then add
Out of scope (the config reader isn't installed at the top of the file, which is what this change states)

2022-09-26 14:42 UTC, CollierCZ commented on docs/src/guides/drupal9/redis.md
> +If you are using Composer to manage your Drupal site (which we recommend), run:
Out of scope (some recommendation maybe should be there)

2022-09-26 14:42 UTC, CollierCZ commented on docs/src/guides/drupal9/simplesaml.md
> +SimpleSAMLphp is able to store its data either on disk or in the Drupal database.
Out of scope

2022-09-26 14:42 UTC, CollierCZ commented on docs/src/guides/drupal9/simplesaml.md
> +Platform.sh strongly recommends using the database.
Out of scope

2022-09-26 14:42 UTC, CollierCZ commented on docs/src/guides/drupal9/solr.md
> +You need to add the [Search API](https://www.drupal.org/project/search_api) and [Search API Solr](https://www.drupal.org/project/search_api_solr) modules to your project. If you are using Composer to
Out of scope

2022-09-26 14:42 UTC, CollierCZ commented on docs/src/guides/micronaut/deploy/customize.md
> +On Platform.sh, we can set the environment variable `JAVA_OPTS` by committing a `.environment` file to the repository's root. Platform.sh runs `source .environment` in the application root when a pro
Out of scope (`is ran` isn't grammatical)

2022-09-26 14:42 UTC, CollierCZ commented on docs/src/guides/quarkus/deploy/customize.md
> +On Platform.sh, we can set the environment variable `JAVA_OPTS` by committing a `.environment` file to the repository's root. Platform.sh runs `source .environment` in the application root when a pro
Out of scope

2022-09-26 14:42 UTC, CollierCZ commented on docs/src/guides/spring/deploy/customize.md
> +On Platform.sh, we can set the environment variable `JAVA_OPTS` by committing a `.environment` file to the repository's root. Platform.sh runs `source .environment` in the application root when a pro
Out of scope

2022-09-26 14:42 UTC, CollierCZ commented on docs/src/guides/spring/deploy/customize.md
> +That gives you a place to do extra environment variable setup prior to the application running, including modifying the system `$PATH` and other shell level customizations.
Out of scope

2022-09-26 14:42 UTC, CollierCZ commented on docs/src/guides/wordpress/composer/migrate.md
> +    Your existing installation of WordPress core is assumed to be in some subdirectory of your repository, such as `wordpress`. When we start managing WordPress with Composer in the next step, *all c
Out of scope (the context of the next step is lost)

2022-09-26 14:42 UTC, CollierCZ commented on docs/src/guides/wordpress/deploy/configure.md
> +Notice that the build `flavor` is set to `composer`, which will automatically download WordPress core, as well as your plugins, themes, and dependencies during the build step as defined in your `comp
Out of scope (the context of the next step is lost)

2022-09-26 14:42 UTC, CollierCZ commented on docs/src/increase-observability/integrate-observability/tideways.md
> +* [Tideways_XHProf](https://github.com/tideways/php-xhprof-extension): The open source version and so no licensing is required (On the downside, less integration services are available). You can use
Out of scope (change in meaning)

2022-09-26 14:42 UTC, CollierCZ commented on docs/src/increase-observability/integrate-observability/tideways.md
> +Give it a few hours to a day to get a decent set of data before checking your Tideways dashboard.
Out of scope

2022-09-26 14:42 UTC, CollierCZ commented on docs/src/integrations/activity/_index.md
> +Any output produced by `console.log` is available in the activity log, and that is the recommended way to debug scripts.
Out of scope

2022-09-26 14:42 UTC, CollierCZ commented on docs/src/integrations/overview.md
> +Platform.sh supports native integrations with multiple services, first and foremost Git hosting services such as GitHub, GitLab, or Bitbucket.
Out of scope (verb and subject don't agree)

2022-09-26 14:42 UTC, CollierCZ commented on docs/src/languages/java/tuning.md
> +Platform.sh will restart the application automatically.
Out of scope (Change in meaning)

2022-09-26 14:42 UTC, CollierCZ commented on docs/src/languages/java/tuning.md
> +We recommend enabling it, as above.
Out of scope (removal of recommendation)

2022-09-26 14:42 UTC, CollierCZ commented on docs/src/security/data-retention.md
> +We have configured our Google Analytics account to store data for 14 months from the time you last accessed our site, which is the minimum Google allows.
Out of scope (security section is different)

2022-09-26 14:42 UTC, CollierCZ commented on docs/src/security/gdpr.md
> +  Our Infrastructure Control Plane is unique to our service and can't be modified by our customers.
Out of scope

2022-09-26 14:42 UTC, CollierCZ commented on docs/src/security/pen-test.md
> +* Application level load testing that don't result in high network load. If the load test may result in the application to be down, we ask to open an urgent ticket as a courtesy 30 to 60 minutes befo
Out of scope

2022-09-26 14:42 UTC, CollierCZ commented on docs/src/security/protective-block.md
> +Platform.sh maintains a database of signatures of known security vulnerabilities in open-source software that are commonly deployed on our infrastructure. The security check only analyze known vulner
Out of scope

2022-09-26 14:42 UTC, CollierCZ commented on docs/src/security/updates.md
> +These do not always happen immediately but when a security vulnerability is identified and released it tends to be fairly soon after.
Out of scope

2022-09-26 15:04 UTC, CollierCZ commented
This also now includes a fix for #2579, which only worked because we had the dependencies already installed in the top-level directory, which isn't the case for people newly coming to the repo.

2022-09-28 10:05 UTC, trolologuy submitted a review, later dismissed
✅

2022-09-29 08:23 UTC, trolologuy approved these changes
✅

2022-09-29 08:23 UTC, merged