📝 Add Console steps for source integrations
platformsh/platformsh-docs pull request #2689
Opened 2022-11-14 15:40 UTC by CollierCZ

## Why

The docs for source integrations incorrectly stated that the CLI was necessary.

## What's changed

- Added steps for Console.
- Tried to organize shortcodes a bit. 
- Took out statements about CLI being necessary.
- Did not validate or standardize the entire pages. Just some small things in passing.

2022-11-15 11:13 UTC, AnouckColson requested changes
Very clear content 👍 .
Kinda fell into the rabbit hole of formatting in the GitHub/GitLab procedures, didn't mean to. Maybe slightly out of scope but easy to fix, so I figured I'd leave my suggestions for you to go over.

2022-11-16 12:52 UTC, CollierCZ commented on docs/src/integrations/source/gitlab.md
>     In the Triggers section choose Push events, Tag push events and Merge Request events.
```suggestion
   In the **Trigger** section select **Push events**, **Tag push events**, and **Merge request events**.
```

2022-11-16 12:53 UTC, CollierCZ commented
There were definitely a lot of style and other issues that I didn't fix because I worried about falling into that hole you mentioned. Definitely good to fix them if it's easy to do so, which it was with your suggestions, so thanks!

2022-11-17 07:28 UTC, AnouckColson requested changes
Sorry I only just realized there were other instances of the syntax being wrong for the display of Console vs CLI tabs in the file. Should all be fixed after this last review.

2022-11-17 07:28 UTC, AnouckColson commented on docs/src/integrations/source/bitbucket.md
> +title:Using the CLI
🛠️ 

```suggestion
title=Using the CLI
```

2022-11-17 07:28 UTC, AnouckColson commented on docs/src/integrations/source/bitbucket.md
> +title:In the Console
🛠️ 

```suggestion
title=In the Console
```

2022-11-17 07:28 UTC, AnouckColson commented on docs/src/integrations/source/github.md
> +title:Using the CLI
🛠️ 

```suggestion
title=Using the CLI
```

2022-11-17 07:28 UTC, AnouckColson commented on docs/src/integrations/source/github.md
> +title:In the Console
🛠️ 

```suggestion
title=In the Console
```

2022-11-17 07:28 UTC, AnouckColson commented on docs/src/integrations/source/gitlab.md
> +title:Using the CLI
🛠️ 

```suggestion
title=Using the CLI
```

2022-11-17 07:28 UTC, AnouckColson commented on docs/src/integrations/source/gitlab.md
> +title:In the Console
🛠️ 

```suggestion
title=In the Console
```

2022-11-21 07:57 UTC, AnouckColson approved these changes
🚀 Ready to go!

2022-11-21 08:15 UTC, merged