:memo: Add Java 19
platformsh/platformsh-docs pull request #2755
Opened 2022-12-14 14:12 UTC by AnouckColson

## Why

## What's changed

Add Java 19 and remove deprecated versions

2022-12-14 14:13 UTC, AnouckColson reviewed
Update based on [this page](https://www.oracle.com/java/technologies/java-se-support-roadmap.html), hope it was the right place to check.

2022-12-14 15:13 UTC, CollierCZ requested changes

2022-12-14 15:13 UTC, CollierCZ commented on docs/data/registry.json
> -        "12",
:clipboard: These should go in the `deprecated` array

2022-12-14 15:13 UTC, CollierCZ commented on docs/data/registry.json
> +        "19"
:clipboard: The build breaks because of this missing comma
```suggestion
        "19",
```

2022-12-15 10:43 UTC, CollierCZ approved these changes

2022-12-15 10:43 UTC, merged