🚚 Deprecate Hugo aliases
platformsh/platformsh-docs pull request #2763
Opened 2022-12-21 09:22 UTC by CollierCZ

## Why

Hugo aliases use meta tags with `refresh` set to true.
For SEO, it's been suggested we should return 301 codes instead.

## What's changed

Changes aliases into redirects and added guidance on why.

2022-12-22 13:29 UTC, trolologuy requested changes
Was there a specific reason to remove the multiline (`|`) descriptions?
Other than that, the redirections work (with a few typos).

2022-12-22 13:29 UTC, trolologuy commented on .platform/routes.yaml
> +      "/guides/general/composer-auth.htmll":  { "to": "/languages/php/composer-auth.html", "code": 301 }
:lady_beetle:
```suggestion
      "/guides/general/composer-auth.html":  { "to": "/languages/php/composer-auth.html", "code": 301 }
```

2022-12-22 13:41 UTC, CollierCZ commented
I feel like multiline markers are confusing for things that shouldn't be longer than one line :shrug:

2023-01-02 08:19 UTC, trolologuy submitted a review, later dismissed
✅ The links work 😎

2023-01-02 08:34 UTC, trolologuy approved these changes
✅

2023-01-02 09:11 UTC, merged