:memo: Add section on paused environments
platformsh/platformsh-docs pull request #2963
Opened 2023-03-10 09:16 UTC by AnouckColson

## Why

Included in the Git 20 release: Development environments that haven't been used for 15 days will now be paused automatically. They can be resume by users themselves (through a redeployment of the environment).

## What's changed

I added a section to the [Manage environments](https://docs.platform.sh/environments.html) page about this feature.

2023-04-25 17:23 UTC, chadwcarlson submitted a review, later dismissed

2023-05-15 12:57 UTC, remilejeune2 commented on docs/src/environments/_index.md
> +You can resume a paused environment at any time.
We could explain that "Pushing new code automatically resume the environment, which can also be resume at any time"

When you are push

2023-05-26 14:43 UTC, chadwcarlson commented on docs/src/environments/_index.md
> +and [Platform.sh API](https://api.platform.sh/).
```suggestion
and the [Platform.sh API](https://api.platform.sh/).
```

2023-05-26 14:43 UTC, chadwcarlson commented on docs/src/environments/_index.md
> +platform p:curl /environments/{{< variable "ENVIRONMENT_ID" >}}/pause -X POST -p {{< variable "PROJECT_ID" >}}
@AnouckColson wasn't there a PR recently that addressed that we want to use expanded commands (`project:curl` vs `p:curl`) preferably? What's our standard?

2023-05-26 14:43 UTC, chadwcarlson commented on docs/src/environments/_index.md
> +platform p:curl /environments/{{< variable "ENVIRONMENT_ID" >}}/resume -X POST -p {{< variable "PROJECT_ID" >}}
Same here

2023-05-26 15:55 UTC, chadwcarlson submitted a review, later dismissed

2023-06-22 08:08 UTC, remilejeune2 requested changes

2023-06-22 08:08 UTC, remilejeune2 commented on docs/src/environments/_index.md
> +In the future, you'll be able to do so in the [CLI](../administration/cli/_index.md) too.
We are in the future. `pause` and `resume` are available in the CLI:
```
  environment:pause                                              Pause an environment
  environment:resume                                             Resume a paused environment
```

2023-06-22 08:08 UTC, remilejeune2 commented on docs/src/environments/_index.md
> +platform project:curl /environments/{{< variable "ENVIRONMENT_ID" >}}/pause -X POST -p {{< variable "PROJECT_ID" >}}
platform environment:pause -p {{< variable "PROJECT_ID" >}} -e {{< variable "ENVIRONMENT_ID" >}}

2023-06-22 08:08 UTC, remilejeune2 commented on docs/src/environments/_index.md
> +platform project:curl /environments/{{< variable "ENVIRONMENT_ID" >}}/resume -X POST -p {{< variable "PROJECT_ID" >}}
platform environment:resume -p {{< variable "PROJECT_ID" >}} -e {{< variable "ENVIRONMENT_ID" >}}

2023-06-22 08:08 UTC, remilejeune2 commented on docs/src/environments/_index.md
> +If you're on a Professional (development) plan,
Is a "development" Plan tied to the Professional tier?

2023-07-26 12:50 UTC, remilejeune2 approved these changes

2023-08-11 12:28 UTC, merged