Update custom-non-production-domains.md
platformsh/platformsh-docs pull request #2996
Opened 2023-03-17 11:27 UTC by callum-hosie

## Why

Adding details for clarity

## What's changed

Added CLI version requirements (v4.3.0+) for customer awareness

2023-03-17 12:25 UTC, chadwcarlson requested changes

2023-03-17 12:25 UTC, chadwcarlson commented on docs/src/domains/steps/custom-non-production-domains.md
> +- The [Platform.sh CLI](../../administration/cli/_index.md) using v4.3.0+
```suggestion
- The [Platform.sh CLI](../../administration/cli/_index.md) (v4.3.0+)
```

2023-03-17 12:48 UTC, AnouckColson approved these changes

2023-03-21 09:07 UTC, AnouckColson approved these changes

2023-03-21 14:43 UTC, chadwcarlson approved these changes

2023-03-21 14:50 UTC, merged