Add version notes to Drupal docs
platformsh/platformsh-docs pull request #3269
Opened 2023-07-07 14:00 UTC by AnouckColson

## Why

Closes #3011 and #3237

## What's changed

Added version notes to Drupal docs (& specific one to SimpleSAML page).

2023-07-26 20:09 UTC, chadwcarlson requested changes
Needs to be the following for all

2023-07-26 20:09 UTC, chadwcarlson commented on docs/src/guides/drupal9/_index.md
> +    body: While this guide focuses on Drupal 9, you can also refer to it when using Drupal 10 as differences in settings are minimal. Note that a Platform.sh [Drupal 10 template](https://github.com/p
```suggestion
    body: While this guide focuses on Drupal 9, you can also refer to it when using Drupal 10 as differences in settings are minimal. Note that a Platform.sh [Drupal 10 template](https://github.com/platformsh-templates/drupal10) is available.
```

2023-07-27 07:24 UTC, AnouckColson commented on docs/src/guides/drupal9/deploy/_index.md
> +    body: While this guide focuses on Drupal 9, you can also refer to it when using Drupal 10 as differences in settings are minimal. Note that a Platform.sh [Drupal 10 template](https://github.com/p
```suggestion
    body: While this guide focuses on Drupal 9, you can also refer to it when using Drupal 10 as differences in settings are minimal. Note that a Platform.sh [Drupal 10 template](https://github.com/platformsh-templates/drupal10) is available.
```

2023-07-27 07:24 UTC, AnouckColson commented on docs/src/guides/drupal9/deploy/configure.md
> +    body: While this guide focuses on Drupal 9, you can also refer to it when using Drupal 10 as differences in settings are minimal. Note that a Platform.sh [Drupal 10 template](https://github.com/p
```suggestion
    body: While this guide focuses on Drupal 9, you can also refer to it when using Drupal 10 as differences in settings are minimal. Note that a Platform.sh [Drupal 10 template](https://github.com/platformsh-templates/drupal10) is available.
```

2023-07-27 07:24 UTC, AnouckColson commented on docs/src/guides/drupal9/deploy/customize.md
> +    body: While this guide focuses on Drupal 9, you can also refer to it when using Drupal 10 as differences in settings are minimal. Note that a Platform.sh [Drupal 10 template](https://github.com/p
```suggestion
    body: While this guide focuses on Drupal 9, you can also refer to it when using Drupal 10 as differences in settings are minimal. Note that a Platform.sh [Drupal 10 template](https://github.com/platformsh-templates/drupal10) is available.
```

2023-07-27 07:24 UTC, AnouckColson commented on docs/src/guides/drupal9/deploy/deploy.md
> +    body: While this guide focuses on Drupal 9, you can also refer to it when using Drupal 10 as differences in settings are minimal. Note that a Platform.sh [Drupal 10 template](https://github.com/p
```suggestion
    body: While this guide focuses on Drupal 9, you can also refer to it when using Drupal 10 as differences in settings are minimal. Note that a Platform.sh [Drupal 10 template](https://github.com/platformsh-templates/drupal10) is available.
```

2023-07-27 07:24 UTC, AnouckColson commented on docs/src/guides/drupal9/deploy/next-steps.md
> +    body: While this guide focuses on Drupal 9, you can also refer to it when using Drupal 10 as differences in settings are minimal. Note that a Platform.sh [Drupal 10 template](https://github.com/p
```suggestion
    body: While this guide focuses on Drupal 9, you can also refer to it when using Drupal 10 as differences in settings are minimal. Note that a Platform.sh [Drupal 10 template](https://github.com/platformsh-templates/drupal10) is available.
```

2023-07-27 07:24 UTC, AnouckColson commented on docs/src/guides/drupal9/multi-site.md
> +    body: While this guide focuses on Drupal 9, you can also refer to it when using Drupal 10 as differences in settings are minimal. Note that a Platform.sh [Drupal 10 template](https://github.com/p
```suggestion
    body: While this guide focuses on Drupal 9, you can also refer to it when using Drupal 10 as differences in settings are minimal. Note that a Platform.sh [Drupal 10 template](https://github.com/platformsh-templates/drupal10) is available.
```

2023-07-27 16:36 UTC, chadwcarlson approved these changes

2023-07-27 16:36 UTC, merged