revamp of multi-app and git submodules doc pages
platformsh/platformsh-docs pull request #3302
Opened 2023-07-26 09:44 UTC by flovntp

## Why

Closes [#{ISSUE_NUMBER}](https://github.com/platformsh/platformsh-docs/issues/3235)

## What's changed

2023-07-28 10:17 UTC, AnouckColson requested changes

2023-07-28 10:17 UTC, AnouckColson commented on docs/src/create-apps/multi-app/routes.md
> +and a Mercure Rocks server app, defined as follows:
```suggestion
In this project, you have a CMS app, two frontend apps (one using Symfony and another using Gatsby),
and a Mercure Rocks server app, defined as follows:
```

2023-07-28 10:17 UTC, AnouckColson commented on docs/src/create-apps/multi-app/routes.md
> +One good example of defining an app with no route is when you use Git submodules and want to enable
@flovntp Unfinished sentence here.

2023-07-28 10:17 UTC, AnouckColson commented on docs/src/development/submodules.md
> +1. Delete information for the submodule you'd like to remove from `.gitmodules` and `.git/config`.
```suggestion
1. In your `.gitmodules` and `.git/config` files, delete the information related to the submodule you want to remove.
```

2023-07-28 10:18 UTC, AnouckColson commented
@flovntp Doc review done, left a few last minute suggestions/comments. Let me know if you see anything amiss!

2023-07-28 12:17 UTC, flovntp commented on docs/src/create-apps/multi-app/routes.md
> +One good example of defining an app with no route is when you use Git submodules and want to enable
finished and pushed

2023-07-28 12:20 UTC, AnouckColson requested changes

2023-07-28 12:20 UTC, AnouckColson commented on docs/src/create-apps/multi-app/routes.md
> +One good example of defining an app with no route is when you [use Git submodules](/create-apps/multi-app/project-structure.html#split-your-code-source-into-multiple-git-submodule-repositories) and w
```suggestion
One good example of defining an app with no route is when you [use Git submodules](/create-apps/multi-app/project-structure.html#split-your-code-source-into-multiple-git-submodule-repositories) and want to [use a source operation to update your submodules](/development/submodules.html#update-submodules).
```

2023-08-02 07:08 UTC, thomasdiluccio submitted a review, later dismissed

2023-08-02 08:20 UTC, merged