White-label migration guide
platformsh/platformsh-docs pull request #3351
Opened 2023-08-11 19:52 UTC by chadwcarlson

## Why

Closes https://github.com/platformsh/platformsh-docs/issues/3347

## What's changed

Continues https://github.com/platformsh/platformsh-docs/pull/3337. Adding a migration guide for white label partners migrating from Platform.sh as an example.

2023-08-16 07:02 UTC, flovntp commented
@chadwcarlson 
strange that the generated url for updated pages is having `src/` in it, it should be 
https://vendor-3347-migrate-nmrndqi-652soceglkw4u.eu-3.platformsh.site/projects/region-migration.html

2023-08-16 08:37 UTC, flovntp commented
Still have an issue in the menu on the right for existing sections.
<img width="285" alt="Capture d’écran 2023-08-16 à 10 36 52" src="https://github.com/platformsh/platformsh-docs/assets/1842696/08caa2fd-7a9a-46b3-b7dd-80f5a426748e">

2023-08-17 12:58 UTC, chadwcarlson commented
@flovntp Try replacing

```
### {{< vendor/name >}}
```

with

```
### {{% vendor/name %}}
```

2023-08-18 09:51 UTC, flovntp commented
@chadwcarlson 
i write a [section in the README file](https://github.com/platformsh/platformsh-docs/tree/vendor/3347-migrate#whitelabel-management) for adding a new whitelabel site (needs to be completed!) and i replace usage of placeholder using `{{< vendor/... >}}` by `{{% vendor/... %}}` in all the file using it (maybe i missed some?). 
And i didn't advise using `{{< vendor/... >}}` in the README section, just a note telling that if using it, they will have issue in the table of contents.

2023-09-08 19:48 UTC, chadwcarlson reviewed
Added some reorganization around the current "Learn" structure.

- For the guide, there seems to be an awful lot included on this single page. Could we split the "what you need to know" into it's own page, and then the actual migration steps in another? Is there too much background here that could be put elsewhere in the docs?
- This guide still needs updates for the final step (push/deploy) as well as updates to the `resources` commands.

2023-09-19 17:48 UTC, gilzow commented
The [/projects/region-migration.html page at step 2](https://docs.upsun.com.vendor-3347-migrate-nmrndqi-652soceglkw4u.eu-3.platformsh.site/projects/region-migration.html#2-create-a-new-project) mentions choosing a development plan, but those plans aren't applicable to Upsun (see #3452 ). 

> start with a Development plan and upsize it

Also, [lower in the page at step 8 ](https://docs.upsun.com.vendor-3347-migrate-nmrndqi-652soceglkw4u.eu-3.platformsh.site/projects/region-migration.html#8-switch-to-the-new-site)it mentions  picking the right "plan size" so we'll need to update this to `container_profile` ?

2023-09-29 14:45 UTC, AnouckColson requested changes

2023-09-29 14:45 UTC, AnouckColson commented on sites/friday/src/learn/tutorials/migrating/platformsh.md
> +{{< /codetabs >}}
```suggestion
Make sure you configure resources (CPU, RAM, disk) per environment for each of your applications and services.
For more information, see how to [manage resources](/manage-resources.md).
```

2023-09-29 14:45 UTC, AnouckColson commented on sites/friday/src/learn/tutorials/migrating/platformsh.md
> +To allocate resources to your application, please see [Resources Allocation doc page](#4-define-resources)
```suggestion
For more information on how you can do so, see how to [manage resources](/manage-resources.md).
```

2023-09-29 16:17 UTC, AnouckColson approved these changes

2023-09-29 16:27 UTC, merged