Document build resources
platformsh/platformsh-docs pull request #3782
Opened 2024-02-15 14:26 UTC by AnouckColson

## Why

Closes #3682 

## What's changed

2024-02-23 10:24 UTC, remilejeune2 requested changes

2024-02-23 10:24 UTC, remilejeune2 commented on sites/friday/src/manage-resources/build-resources.md
> +{{% vendor/cli %}} project:curl capabilities -X PATCH -d '{"build_resources": {"enabled": true}}'
The end user cannot enable the capability, it will be done by default on Upsun.

2024-02-23 10:24 UTC, remilejeune2 commented on sites/platform/src/create-apps/build-resources.md
> +title: Build resources
This feature is not available on Platform.sh, only on Upsun.

2024-03-22 10:11 UTC, remilejeune2 approved these changes

2024-03-25 18:28 UTC, chadwcarlson approved these changes

2024-03-25 18:43 UTC, merged