first draft for composable image on Upsun side (only for now)
platformsh/platformsh-docs pull request #3879
Opened 2024-03-20 11:20 UTC by flovntp

## Why

Closes #{ISSUE_NUMBER}

## What's changed

2024-03-26 09:29 UTC, lolautruche commented
Here are a few comments:

* "Built-in Image" ➡️ *Single-runtime Image*, as suggested by @AnouckColson and @chadwcarlson 
* "Composable image is a new way to install" ➡️ We should refrain ourselves to use "new", as this doc page is going to last
* We're *not* using NixOS, only *Nix*
* I'm not sure we should describe Nix and NixOS in the doc. I'd better do this in a blog post instead. We may just mention that the Composable Image is built on top of Nix, and that we can install packages from NixPkgs.
* We should mention that the first element of the list will be considered as the "Primary runtime". It's especially important for PHP as PHP-FPM is started automatically _only_ if PHP is specified as the first item.
* `stack` row in the properties table:
  * Type: I'd rephrase to "An array of Nix packages" (+ link to the `stack` doc section)
  * Description: "A list of packages from our collection of supported runtimes and/or from NixPkgs".
* `stack` section:
  * We should probably make a clearer distinction between runtimes and packages
  * "Available tools and their supported version": I think we can remove this part
  * We should have a dedicated section for PHP, presenting all the peculiarities (inner configuration with subsections, how to add an extension...)

2024-03-26 09:51 UTC, lolautruche requested changes

2024-03-26 09:51 UTC, lolautruche commented on sites/friday/src/create-apps/app-reference/composable-image.md
> +Python - for the frontend of a deployed site.
```suggestion
It is possible to use multiple runtimes in a single application container, e.g. PHP, NodeJS and Python, while remaining in control of their versions.
```

2024-03-26 09:51 UTC, lolautruche commented on sites/friday/src/create-apps/app-reference/composable-image.md
> +In this case, the unified `{{< vendor/configfile "app" >}}` file would look like:
```suggestion
For example, the unified `{{< vendor/configfile "app" >}}` file may look like the following:
```

2024-03-26 09:51 UTC, lolautruche commented on sites/friday/src/create-apps/app-reference/composable-image.md
> +| `stack`            | An array of [NixOs runtimes](#stack)                | Yes      | No               | The list of runtime images to use with a specific app. Format: <br>`<runtime>@<version>`.
```suggestion
| `stack`            | An array of [Nix packages](#stack)                | Yes      | No               | A list of packages from our collection of supported runtimes and/or from NixPkgs.                                                                                                                                                                        |
```

2024-03-26 09:51 UTC, lolautruche commented on sites/friday/src/create-apps/app-reference/composable-image.md
> +as a YAML array, that you would like to install in your application container.
```suggestion
The ``stack`` keyword is used to define the list of all the packages your application needs to work, 
including language runtimes (e.g. `php`, `nodejs`, `python`...) and other utilities (e.g. `imagemagick`, `graphviz`, `yarn`...).
This list is defined as a YAML array.
```

2024-03-26 09:51 UTC, lolautruche commented on sites/friday/src/create-apps/app-reference/composable-image.md
> +Security and other patches are taken care of for you automatically.
This is only true for the runtimes.
As for the other packages, it's up to the Nix maintainers.

2024-03-26 09:51 UTC, lolautruche commented on sites/friday/src/create-apps/app-reference/composable-image.md
> +| [Yarn](https://classic.yarnpkg.com/)                                 | `yarn`        | none                    |
I'm not sure we need to specify this.

2024-03-26 09:51 UTC, lolautruche commented on sites/friday/src/create-apps/app-reference/composable-image.md
> +{{% /note %}}
This should probably go to the PHP page

2024-03-26 09:51 UTC, lolautruche commented on sites/friday/src/create-apps/app-reference/composable-image.md
> +{{< /codetabs >}}
This should probably go to the Python page

2024-03-26 09:51 UTC, lolautruche commented on sites/friday/src/create-apps/app-reference/composable-image.md
> +Alternatively, if you need to include configuration options for your extensions, use either your ``php.ini`` file or [environment variables](/development/variables/set-variables.md):
Should also go to the PHP page

2024-03-28 19:24 UTC, chadwcarlson commented
Questions from review:

- [`socket_family` default](https://composable-image-o3lpfiy-ucq44jg6ofare.eu-5.platformsh.site/create-apps/app-reference/composable-image.html#upstream) - Currently reads "Defaults to tcp for all [image types](https://composable-image-o3lpfiy-ucq44jg6ofare.eu-5.platformsh.site/create-apps/app-reference/composable-image.html#types) except PHP; for PHP image types the default is unix." Does the default value change at all for different stacks, or for the composable image does this just always default to `tcp`?
- [`protocol` default](https://composable-image-o3lpfiy-ucq44jg6ofare.eu-5.platformsh.site/create-apps/app-reference/composable-image.html#upstream) - Same here, currently reads "Default varies based on [image type](https://composable-image-o3lpfiy-ucq44jg6ofare.eu-5.platformsh.site/create-apps/app-reference/composable-image.html#types)." Is this true when `stack` is used? Is there a consistent default in the case of `stack`?

2024-04-01 16:23 UTC, chadwcarlson commented on sites/platform/src/languages/php/_index.md
> +  frontend:
This is Upsun, not Platform.sh config here.

2024-04-02 14:42 UTC, merged